Keyboard download availability API
keymanapp/downloads.keyman.com pull request #12
Opened 2017-11-17 07:52 UTC by mcdurdin

2017-11-17 08:50 UTC, jahorton approved these changes
LGTM.

2017-11-17 08:57 UTC, darcywong00 requested changes
1. Updates to README.md
2. Is there going to be a folder for https://downloads.keyman.com/keyboard/ ? If so, that'll need .htaccess, right?

2017-11-17 08:57 UTC, darcywong00 commented on _tools/syncfiles.txt
> +api/util.php
This impacts the [Files to Upload](https://github.com/keymanapp/downloads.keyman.com#files-to-upload) section of README.md

2017-11-20 01:05 UTC, mcdurdin commented
1. Resolved.
2. Yes, added the .htaccess (for `Options +Indexes` support) to keyboards/

2017-11-20 01:15 UTC, darcywong00 approved these changes
lgtm

2017-11-20 01:18 UTC, merged